### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by WardLT** [materials-data-facility/battery-data-toolkit#3]
Need to set up Travis CI, coverals, etc for this repo

**Comment by jkubal2** [comment]
So from what I see, Travis CI is a UI to test the code from github?

**Comment by WardLT** [comment]
Yes, it lets you run tests each time you push a new commit to the repo. You can also make it do some other utility tasks, like publish your code to PyPI for specific versions.

If you're curious, I'm planning on making something similar to dlhub_sdk: https://github.com/DLHub-Argonne/dlhub_sdk
